### ISSUE TITLE
gitignore suggestions

### ISSUE THREAD

**Issue by damienpontifex** [michaelarg/mysunjourney#4]
I see you've checked in .pyc files - look at https://www.gitignore.io/api/python for python gitignore rules.

then `git rm --cached *.pyc` to remove them from git

Feel free to also ignore me as it's your project :) I'm just here checking out your work

**Comment by michaelarg** [comment]
I appreciate you taking the time to look. 

Yes my initial commit was before I added my .gitignore file so i'll go back and remove them. 

Thanks!
